name: Change Checker
on:
  pull_request:
    types: [
      opened,
      edited,
      reopened,
      synchronize
    ]

jobs:
  change-checker:
    name: Change Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@modyolabs'
      - name: Verify libraries changes
        run: rush change -v
