name: Checks
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
      - develop

jobs:
  checks:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: pnpm build
      - name: Lint packages
        run: |
          pnpm eslint
          pnpm stylelint
      - name: Test packages
        run: pnpm test
