name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  process:
    name: Version and Publish
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@modyolabs'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: pnpm exec lerna run build --no-private
      - name: Version and publish packages
        run: |
          pnpm set @modyolabs:registry=https://npm.pkg.github.com/
          pnpm set "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}"
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          pnpm exec lerna publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
