name: Release
on:
  push:
    branches:
      - master
#  pull_request:
#    types: [closed]
#    branches:
#      - master

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  process:
    name: Version and Publish
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@modyolabs'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: pnpm exec lerna run build --no-private
      - name: Version packages
        run: pnpm exec lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish packages
        run: pnpm exec lerna publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
