name: Storybook
on:
  push:
    branches:
      - feat/storybook-publish

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Checkout packages submodules.
        run: git submodule update --init packages/stencil-eslint-plugin
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@modyo-dynamic'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build packages
        run: pnpm build
      - name: Build storybook
        run: pnpm build:storybook:react
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: libraries/modyo-design-system-react/docs
          CLEAN: true
          TARGET_FOLDER: docs
          COMMIT_MESSAGE: 'doc: update storybook'
