name: Version Packages
on:
  pull_request:
    branches:
      - master
    types: [
      opened,
      edited,
      synchronize
    ]

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  version-library:
    name: Versioning Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@modyolabs'
      - name: Verify libraries changes
        run: node common/scripts/install-run-rush.js change -v
      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install
        env:
          # And add the additional registry token here:
          # FORTAWESOME_TOKEN: ${{secrets.FORTAWESOME_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
      - name: Versioning
        run : |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          node common/scripts/install-run-rush.js publish --apply --target-branch $TARGET_BRANCH
        env:
          TARGET_BRANCH: ${{ github.head_ref }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
